// Generated by scripts/sync-release.ts from the AltStore manifest.
// Do not edit by hand — run `bun run sync:release` instead.

export const release = {
	version: '1.0.3',
	minOS: 'iOS 15+',
	size: '~9 MB',
	ipaUrl: 'https://github.com/xibrox/Shirox/releases/download/beta/Shirox.ipa'
} as const;
