#!/usr/bin/env bun
/**
 * Pulls the release facts the site displays out of the AltStore source manifest,
 * so cutting a release is the only step — no matching hand edit here.
 *
 * Writes `src/lib/release.generated.ts`, which is committed. Runs automatically
 * before `bun run build`; on its own via `bun run sync:release`.
 *
 * Network or shape failures leave the committed file untouched and exit 0. A
 * version number one release stale is a far better outcome than a broken
 * deploy, and the warning says which of the two you got.
 */

/** The same manifest AltStore reads. Mirrored as SOURCE_URL in src/lib/content.ts. */
const SOURCE_URL = 'https://raw.githubusercontent.com/xibrox/Shirox/refs/heads/main/apps.json';
const OUT = new URL('../src/lib/release.generated.ts', import.meta.url);

type ManifestVersion = {
	version: string;
	buildVersion?: string;
	date?: string;
	downloadURL: string;
	size: number;
	minOSVersion: string;
};

type ManifestApp = {
	bundleIdentifier: string;
	versions: ManifestVersion[];
};

type Manifest = {
	featuredApps?: string[];
	apps: ManifestApp[];
};

/** Numeric per segment, so 1.0.10 sorts above 1.0.9 rather than below it. */
function compareVersions(a: string, b: string) {
	const left = a.split('.').map(Number);
	const right = b.split('.').map(Number);

	for (let i = 0; i < Math.max(left.length, right.length); i++) {
		const delta = (left[i] ?? 0) - (right[i] ?? 0);
		if (delta) return delta;
	}
	return 0;
}

/**
 * The manifest happens to list newest first, but that is a convention rather
 * than a guarantee, so pick explicitly: newest date wins, version breaks ties.
 */
function newest(versions: ManifestVersion[]) {
	return versions.reduce((best, candidate) => {
		const byDate = Date.parse(candidate.date ?? '') || 0;
		const bestDate = Date.parse(best.date ?? '') || 0;
		if (byDate !== bestDate) return byDate > bestDate ? candidate : best;
		return compareVersions(candidate.version, best.version) > 0 ? candidate : best;
	});
}

/** Decimal MB — the unit download sizes are quoted in everywhere else. */
function formatSize(bytes: number) {
	return `~${Math.round(bytes / 1e6)} MB`;
}

/** "15.0" reads as a precision the app does not actually require. */
function formatMinOS(version: string) {
	return `iOS ${version.replace(/(\.0+)+$/, '')}+`;
}

function pickApp(manifest: Manifest) {
	const featured = manifest.featuredApps?.[0];
	const app = manifest.apps?.find((a) => a.bundleIdentifier === featured) ?? manifest.apps?.[0];

	if (!app?.versions?.length) throw new Error('no app with versions in the manifest');
	return app;
}

function render(latest: ManifestVersion) {
	const fields = {
		version: latest.version,
		minOS: formatMinOS(latest.minOSVersion),
		size: formatSize(latest.size),
		ipaUrl: latest.downloadURL,
	};

	for (const [key, value] of Object.entries(fields)) {
		if (typeof value !== 'string' || !value || value.includes('undefined')) {
			throw new Error(`manifest is missing a usable value for ${key}`);
		}
	}

	return `// Generated by scripts/sync-release.ts from the AltStore manifest.
// Do not edit by hand — run \`bun run sync:release\` instead.

export const release = {
	version: '${fields.version}',
	minOS: '${fields.minOS}',
	size: '${fields.size}',
	ipaUrl: '${fields.ipaUrl}'
} as const;
`;
}

async function main() {
	const response = await fetch(SOURCE_URL, {
		signal: AbortSignal.timeout(15_000),
		headers: { accept: 'application/json' },
	});

	if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);

	const latest = newest(pickApp((await response.json()) as Manifest).versions);
	const next = render(latest);
	const current = await Bun.file(OUT)
		.text()
		.catch(() => '');

	if (current === next) {
		console.log(`release: already current at v${latest.version}`);
		return;
	}

	await Bun.write(OUT, next);
	console.log(`release: synced to v${latest.version} (${formatSize(latest.size)})`);
}

try {
	await main();
} catch (error) {
	const reason = error instanceof Error ? error.message : String(error);
	const exists = await Bun.file(OUT).exists();

	if (!exists) {
		console.error(`release: cannot reach the manifest (${reason}) and no generated file exists.`);
		process.exit(1);
	}

	console.warn(`release: sync skipped (${reason}) — building with the committed values.`);
}
